#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
APP_HOME=$(cd "${0%/*}" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS=$(uname)
case $OS in
  CYGWIN* ) CYGWIN=true ;;
  Darwin* ) DARWIN=true ;;
  MSYS* | MINGW* ) MSYS=true ;;
  NONSTOP* ) NONSTOP=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD" != "maximum" ] ; then
    MAX_FD_LIMIT=$MAX_FD
else
    MAX_FD_LIMIT=$(ulimit -H -n) || exit
fi

if [ "$MAX_FD_LIMIT" = "unlimited" ] ; then
    MAX_FD_LIMIT=65536
fi

if [ "$MAX_FD" = "maximum" ] ; then
    ulimit -n "$MAX_FD_LIMIT" || warn "Could not set maximum file descriptor limit: $MAX_FD_LIMIT"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the classpath
#   * the main class name
#   * default JVM options
#   * environment variables GRADLE_OPTS, JAVA_OPTS, and GRADLE_OPTS.

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Stop when encountering xargs that are not POSIX compliant.
if ! command -v xargs >/dev/null 2>&1 ; then
  die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In POSIX shells, we can just feed the result to "set --".

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed 's~[^-[:alnum:]+,./:=@_]~\\&~g' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
